SCREEN_WIDTH = 800
SCREEN_HEIGHT = 500

FPS = 60

MOVE_PLAYER_SPEED = 8
BULLET_SPEED = 15
MOVE_ENEMY_WITH_ONE_BARREL_SPEED = 5
MOVE_ENEMY_WITH_TWO_BARREL_SPEED = 3

BASE_HEALTH = 100

ENABLE_ENEMIES = True
